// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © k6041535

//@version=5
strategy("Complex Strategy (Reversed)", shorttitle="Complex (Reversed)", overlay=true)

length_ema200 = 200
length_sma1 = 5
length_sma2 = 10
length_sma3 = 15
fastlen = 12  
slowlen = 26 
siglen = 9   

ema200 = ta.ema(close, length_ema200)
sma1 = ta.sma(close, length_sma1)
sma2 = ta.sma(close, length_sma2)
sma3 = ta.sma(close, length_sma3)

[macdLine, signalLine, _] = ta.macd(close, fastlen, slowlen, siglen)

long_condition = close < ema200 and sma1 < sma2 and sma2 < sma3 and macdLine < signalLine
short_condition = close > ema200 and sma1 > sma2 and sma2 > sma3 and macdLine > signalLine

trade_size = input.float(50, title="交易金額")
leverage = input.int(15, title="倍率")

entry_price = close
qty_trade_size = (trade_size * leverage) 

if (short_condition)
    strategy.entry("Long", strategy.long, qty=(qty_trade_size / entry_price))
 
if (long_condition)
    strategy.entry("Short", strategy.short, qty=(qty_trade_size / entry_price))

stop_loss_percent = input(1, title="止损百分比")
take_profit_percent = input(1.5, title="止盈百分比")

// strategy.exit("Take Profit/Stop Loss", from_entry="Long", when=short_condition, trail_offset=take_profit_percent, trail_price=entry_price)
// strategy.exit("Take Profit/Stop Loss", from_entry="Short", when=long_condition, trail_offset=take_profit_percent, trail_price=entry_price)
// strategy.exit("Stop Loss", from_entry="Long", when=short_condition, trail_offset=stop_loss_percent, trail_price=entry_price)
// strategy.exit("Stop Loss", from_entry="Short", when=long_condition, trail_offset=stop_loss_percent, trail_price=entry_price)
